### ISSUE TITLE
Message: unknown error: unable to discover open pages

### ISSUE THREAD

**Issue by Onyx-Ind** [farshadz1997/Microsoft-Rewards-bot#113]
Hello, I've recently had no problems with the script itself but it has started to fail. I have the script running on Ubuntu 
22.04.2 LTS ARM64 in the tmux session and I usually have ProtonVPN connected. Would you mind helping me with my issue?

**Details:**
The script is first stuck at `********************(Email Here)********************` and spits out the error.

**Error:**
```
Message: unknown error: unable to discover open pages
Stacktrace:
#0 0xaaaabc053664 <unknown>
#1 0xaaaabbe4194c <unknown>
#2 0xaaaabbe69668 <unknown>
#3 0xaaaabbe65854 <unknown>
#4 0xaaaabbe62d24 <unknown>
#5 0xaaaabbe9d810 <unknown>
#6 0xaaaabbe6c28c <unknown>
#7 0xaaaabbe6d2e8 <unknown>
#8 0xaaaabc0a1238 <unknown>
#9 0xaaaabc0a3cd4 <unknown>
#10 0xaaaabc0a4410 <unknown>
#11 0xaaaabc08bea8 <unknown>
#12 0xaaaabc0a4bc0 <unknown>
#13 0xaaaabc07e054 <unknown>
#14 0xaaaabc0c5610 <unknown>
#15 0xaaaabc0c5790 <unknown>
#16 0xaaaabc0de3d0 <unknown>
#17 0xffff94dda624 <unknown>
#18 0xffff9490c49c <unknown>


Traceback (most recent call last):
  File "/home/ubuntu/(user)/ms_rewards_farmer.py", line 1483, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
  File "/home/ubuntu/(user)/ms_rewards_farmer.py", line 88, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open pages
Stacktrace:
#0 0xaaaabc053664 <unknown>
#1 0xaaaabbe4194c <unknown>
#2 0xaaaabbe69668 <unknown>
#3 0xaaaabbe65854 <unknown>
#4 0xaaaabbe62d24 <unknown>
#5 0xaaaabbe9d810 <unknown>
#6 0xaaaabbe6c28c <unknown>
#7 0xaaaabbe6d2e8 <unknown>
#8 0xaaaabc0a1238 <unknown>
#9 0xaaaabc0a3cd4 <unknown>
#10 0xaaaabc0a4410 <unknown>
#11 0xaaaabc08bea8 <unknown>
#12 0xaaaabc0a4bc0 <unknown>
#13 0xaaaabc07e054 <unknown>
#14 0xaaaabc0c5610 <unknown>
#15 0xaaaabc0c5790 <unknown>
#16 0xaaaabc0de3d0 <unknown>
#17 0xffff94dda624 <unknown>
#18 0xffff9490c49c <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/(user)/ms_rewards_farmer.py", line 1618, in <module>
    main()
  File "/home/ubuntu/(user)/ms_rewards_farmer.py", line 1602, in main
    farmer()
  File "/home/ubuntu/(user)/ms_rewards_farmer.py", line 1562, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
```

**Versions:**
`chromium-browser --version`: Chromium 110.0.5481.100 snap
`chromedriver -v`: ChromeDriver 110.0.5481.100 (4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14})

**Comment by farshadz1997** [comment]
Hello, it seems like the problem is from Chrome driver version 110, someone reported this bug for version 110
https://github.com/SeleniumHQ/selenium/issues/11634#issue-1576700274

**Comment by Onyx-Ind** [comment]
Gotcha, thank you!
