### ISSUE TITLE
UnboundLocalError: local variable 'browser' referenced before assignment

### ISSUE THREAD

**Issue by Sentaku1129** [farshadz1997/Microsoft-Rewards-bot#114]
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 1483, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
  File "ms_rewards_farmer.py", line 88, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 1618, in <module>
    main()
  File "ms_rewards_farmer.py", line 1602, in main
    farmer()
  File "ms_rewards_farmer.py", line 1562, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment

**Comment by farshadz1997** [comment]
Check #96

**Comment by farshadz1997** [comment]
Closing as there is already another issue with this topic.
