### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

### ISSUE THREAD

**Issue by stylinnile** [farshadz1997/Microsoft-Rewards-bot#131]
I get the error:
```
DevTools listening on ws://127.0.0.1:50721/devtools/browser/04baba9f-194b-4132-af29-92edffc97778
[LOGIN] Logging-in...
[LOGIN] Writing email...
Traceback (most recent call last):
  File "C:\Users\trevo\msfarm\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\trevo\msfarm\ms_rewards_farmer.py", line 46, in login
    browser.find_element_by_name("loginfmt").send_keys(email)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'
PS C:\Users\trevo\msfarm>
```

I am probably doing something wrong but I dont see a similar error posted so any help would be appreciated!

**Comment by stylinnile** [comment]
I reinstalled and now get:
```
PS C:\Users\trevo\msfarm> python ms_rewards_farmer.py --edge
Traceback (most recent call last):
  File "C:\Users\trevo\msfarm\ms_rewards_farmer.py", line 12, in <module>
    from notifiers import get_notifier
ModuleNotFoundError: No module named 'notifiers'
PS C:\Users\trevo\msfarm>
```

**Comment by farshadz1997** [comment]
run ```pip install -r requirements.txt```

**Comment by stylinnile** [comment]
Yep just figured it out! was just going to close it thanks for the swift response!
