### ISSUE TITLE
whats wrong im new to coding pls help

### ISSUE THREAD

**Issue by jakubadkinnnnn** [farshadz1997/Microsoft-Rewards-bot#137]
[91m
    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗ 
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝[00m
[95m            by @Charlesbel upgraded by @Farshadz1997        version 2.1
[00m
[92m
[LOGS] Logs loaded successfully.
[00m
[93m********************Your Email********************[00m

Traceback (most recent call last):
  File "C:\Users\jakub\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/jakub/bot.py", line 1561, in farmer
    browser = browserSetup(False, PC_USER_AGENT, account.get('proxy', None))
  File "C:/Users/jakub/bot.py", line 103, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "C:\Users\jakub\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\jakub\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\jakub\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/jakub/bot.py", line 1690, in <module>
    main()
  File "C:/Users/jakub/bot.py", line 1674, in main
    farmer()
  File "C:/Users/jakub/bot.py", line 1634, in farmer
    browser.quit()
UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value

**Comment by farshadz1997** [comment]
Bot couldn't locate webdriver executable, download it and put it in bot directory

**Comment by jakubadkinnnnn** [comment]
how to download it

**Comment by farshadz1997** [comment]
please read readme, I explained everything.

**Comment by jakubadkinnnnn** [comment]
i have already downloaded webdriver

**Comment by farshadz1997** [comment]
extract executable file in bot directory.
