### ISSUE TITLE
Using --session --headless crashes

### ISSUE THREAD

**Issue by ttuleyb** [farshadz1997/Microsoft-Rewards-bot#139]
This isn't a duplicate of Issue #96 I did check to confirm that both my chrome driver and version are matching (111.0.5563.64).
This happens only when using --session and --headless at the same time.
Platform: ARM64 MacOS M1 Macbook Air.

```
    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗ 
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version 2.1

[INFO] everyday: False
[INFO] headless: True
[INFO] session: True
[INFO] error: False
[INFO] fast: False
[INFO] telegram: None
[INFO] discord: None
[INFO] edge: False
[INFO] shutdown: None
[INFO] account_browser: None
[INFO] start_at: None
[INFO] autoexit: False

[LOGS] Logs loaded successfully.

********************xxx@x********************


Traceback (most recent call last):
  File "/Users/user/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 1560, in farmer
    browser = browserSetup(False, PC_USER_AGENT, account.get('proxy', None))
  File "/Users/user/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 102, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
0   chromedriver                        0x00000001034072c8 chromedriver + 4928200
1   chromedriver                        0x000000010337f273 chromedriver + 4371059
2   chromedriver                        0x0000000102fc7777 chromedriver + 472951
3   chromedriver                        0x0000000102ff4407 chromedriver + 656391
4   chromedriver                        0x0000000102feffe1 chromedriver + 638945
5   chromedriver                        0x000000010303e845 chromedriver + 960581
6   chromedriver                        0x0000000103034cb3 chromedriver + 920755
7   chromedriver                        0x0000000102ffb9eb chromedriver + 686571
8   chromedriver                        0x0000000102ffcfe4 chromedriver + 692196
9   chromedriver                        0x00000001033d290e chromedriver + 4712718
10  chromedriver                        0x00000001033d7e42 chromedriver + 4734530
11  chromedriver                        0x00000001033e068f chromedriver + 4769423
12  chromedriver                        0x00000001033d8e90 chromedriver + 4738704
13  chromedriver                        0x00000001033a9815 chromedriver + 4544533
14  chromedriver                        0x00000001033faf58 chromedriver + 4878168
15  chromedriver                        0x00000001033fb0d5 chromedriver + 4878549
16  chromedriver                        0x000000010340f84e chromedriver + 4962382
17  libsystem_pthread.dylib             0x00007ff8141f9259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff8141f4c7b thread_start + 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 1689, in <module>
    main()
  File "/Users/user/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 1673, in main
    farmer()
  File "/Users/user/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 1633, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
```

**Comment by farshadz1997** [comment]
I checked it, when using session and headless Web driver needs to create some files for profile such as favorite list password, etc. when using headless it cannot create those files and raises an error. try to run the account without headless to create a session after that use headless.

**Comment by Not-Dhanraj** [comment]
> I checked it, when using session and headless Web driver needs to create some files for profile such as favorite list password, etc. when using headless it cannot create those files and raises an error. try to run the account without headless to create a session after that use headless.

I've tried it multiple times, it doesn't help either. I have tried without headless also but it just doesn't work and throws the error
