### ISSUE TITLE
How can I run this script using crontab and Xvfb?

### ISSUE THREAD

**Issue by sanzo-mlgb** [farshadz1997/Microsoft-Rewards-bot#142]
I have a raspberry, running Raspberry Pi OS without a GUI

because in the README I see "Do not use headless mode", I used Xvfb, so I can run this script in the terminal without the headless parameter, everything works normal.

But when I try to use crontab to run the script, the program cannot run any further.

Here's the script I use to write the run log to a msrbpy file. 

```
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export DISPLAY=:99
cd /root/msrb && /usr/bin/python ms_rewards_farmer.py --autoexit >> runninglog 2>&1
```

When the specified time is reached, there is only one line in the runninglog file
```
sh: 1: color: not found"
```

This line of text will also appear at the first time when using the terminal to run the program, but the logo of this program will appear immediately afterwards, and continue to work normally

Where am I doing wrong? Is there a way for me to run this script on a system without a GUI?

English is not my native language, so the above text is obtained by using translation software, sorry if it causes difficulty in understanding

**Comment by sanzo-mlgb** [comment]
Sorry, I made a mistake. Although I can’t see the following logs in the runninglog file, I can still see that chrome is running through the` top `command. I think the program should be running normally. Is there any way to be able to save the run log to a file?

**Comment by farshadz1997** [comment]
Sorry, I don't have any experice with Raspberry Pi, I let this issue remain open maybe someone could help you with that.

**Comment by sanzo-mlgb** [comment]
> Sorry, I don't have any experice with Raspberry Pi, I let this issue remain open maybe someone could help you with that.

I ended up running this program on Linux without a GUI using `Xvfb` and `xvfbwrapper` without the `--headless` parameter

first:
```
apt install xvfb
```
Then:
```
pip install xvfbwrapper
```
at the top of ms_rewards_farmer.py, import xvfbwrapper
```
from xvfbwrapper import Xvfb
```
at the end of ms_rewards_farmer.py, Include `main()` in `with Xvfb() as xvfb:`, like this:
```
if __name__ == '__main__':
    with Xvfb() as xvfb:
        main()
```

I don't know how to use git, so if you find this method useful, you can add it to the README or program.

**Comment by Prabh-Saini** [comment]
@micheleietri this should've been fixed in #186

**Comment by micheleietri** [comment]
On my rasp3 it works fine now yes, still trying to figure it out for rasp1 too! thanks for mentioning me btw!

**Comment by micheleietri** [comment]
Still in error with this trace

Traceback (most recent call last):
  File "/home/pi/ms-farmer/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2179, in farmer
    browser = browserSetup(False, PC_USER_AGENT, account.get('proxy', None))
  File "/home/pi/ms-farmer/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 120, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x000000a48e58 <unknown>
#1 0x0000007ef264 <unknown>
#2 0x00000081afa8 <unknown>
#3 0x000000817230 <unknown>
#4 0x00000085e090 <unknown>
#5 0x000000855018 <unknown>
#6 0x000000822380 <unknown>
#7 0x000000823668 <unknown>
#8 0x000000a97818 <unknown>
#9 0x000000a9a6e8 <unknown>
#10 0x000000a99f8c <unknown>
#11 0x000000a9aea8 <unknown>
#12 0x000000a808e8 <unknown>
#13 0x000000a9b320 <unknown>
#14 0x000000a72a50 <unknown>
#15 0x000000abb2f8 <unknown>
#16 0x000000abb47c <unknown>
#17 0x000000ad72f8 <unknown>
#18 0x000076edc310 start_thread
#19 0x000000000000 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/ms-farmer/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2374, in <module>
    main()
  File "/home/pi/ms-farmer/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2341, in main
    farmer()
  File "/home/pi/ms-farmer/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2289, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
local variable 'browser' referenced before assignment
press Enter to close...
