### ISSUE TITLE
 Microsoft-Rewards-Bot crashes after handling 14 accounts: Need to fix the capacity issue

### ISSUE THREAD

**Issue by Albertjokers** [farshadz1997/Microsoft-Rewards-bot#185]
I've been trying to use the bot to farm on 18 Microsoft accounts, but it crashes when attempting to run 14 accounts. As an alternative, I tried using the GUI version, which does work but is slow and buggy. For example, it can get stuck on a login page or create duplicate tabs, causing it to freeze.

As for the non-GUI version, if you add more than 14 accounts to the accounts.json file, the bot crashes when attempting to run the farm.

I just wanted to bring this issue to your attention so that it can be addressed (if possible), as having a bot that can handle more accounts without crashing would be more efficient.

Thank you for your attention to this matter.

**Comment by Albertjokers** [comment]
Traceback (most recent call last):
  File "C:\Users\Account\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2339, in <module>
    main()
  File "C:\Users\Account\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2279, in main
    loadAccounts()
  File "C:\Users\Account\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2118, in loadAccounts
    ACCOUNTS = json.load(open(ACCOUNTS_PATH, "r"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Account\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Account\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Account\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Account\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 89 column 29 (char 4396)
Invalid control character at: line 89 column 29 (char 4396)
press Enter to close...

**Comment by farshadz1997** [comment]
There's an invalid character at line 89 of your accounts file, check that
