### ISSUE TITLE
WebDriver issue on recent update

### ISSUE THREAD

**Issue by HQModz** [farshadz1997/Microsoft-Rewards-bot#192]
Hello,

I just updated the bot and I am getting this webdriver error. I have tried adding the directory to PATH with the proper chromedriver file that matches my browser version, but it is still not working. If I revert back to a bot version from a week ago it runs fine. I usually use 'sudo apt install chromium-driver' but that doesn't seem to work anymore. If I am adding it to PATH incorrectly, can you please explain how to properly install  the chromedriver? I haven't had any issues for months until this recent bot update. I am on Linux/Debian (Raspberry Pi Desktop.) Thank you!

![Screenshot_36](https://user-images.githubusercontent.com/51813680/228502786-5c5829c7-088c-4657-b3aa-5e9b2deec965.jpg)

**Comment by Prabh-Saini** [comment]
Are you using manual webdriver or automatic webdriver?

**Comment by farshadz1997** [comment]
I think it's come from webdriver manager, I'll try to fix it

**Comment by farshadz1997** [comment]
@HQModz try run with ```--no-webdriver-manager```

**Comment by HQModz** [comment]
> @HQModz try run with `--no-webdriver-manager`

That worked, thanks! Is there a reason it's not working without this argument?

**Comment by Prabh-Saini** [comment]
because raspberry pi doesnt have an official webdriver (because it runs on arm), causing it to fail

**Comment by HQModz** [comment]
It's not actually a Pi device, I am just running Raspberry Pi Desktop for PC on a virtual machine. Not sure if that matters. Here are some more errors:

`[WDM] - Downloading: 100%|█████████████████| 6.83M/6.83M [00:04<00:00, 1.55MB/s]
Traceback (most recent call last):
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2287, in farmer
    browser = browserSetup(False, PC_USER_AGENT, account.get('proxy', None))
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 127, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/admin/.wdm/drivers/chromedriver/linux64/111.0.5563/chromedriver unexpectedly exited. Status code was: 127



Traceback (most recent call last):
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2287, in farmer
    browser = browserSetup(False, PC_USER_AGENT, account.get('proxy', None))
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 127, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/admin/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /home/admin/.wdm/drivers/chromedriver/linux64/111.0.5563/chromedriver unexpectedly exited. Status code was: 127


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2483, in <module>
    main()
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2450, in main
    farmer()
  File "/home/admin/Desktop/Bots/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 2397, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
local variable 'browser' referenced before assignment
press Enter to close...
`
