### ISSUE TITLE
mobile agent preventiung script from running

### ISSUE THREAD

**Issue by yoyodolo** [farshadz1997/Microsoft-Rewards-bot#25]
Traceback (most recent call last):
  File "F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1119, in <module>
    ACCOUNTS = json.load(open(account_path, "r"))
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 5 (char 75)
PS F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master> python ms_rewards_farmer.py --fast
Traceback (most recent call last):
  File "F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1119, in <module>
    ACCOUNTS = json.load(open(account_path, "r"))
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 5 (char 75)
PS F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master> python ms_rewards_farmer.py --fast
Traceback (most recent call last):
  File "F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1119, in <module>
    ACCOUNTS = json.load(open(account_path, "r"))
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 5 (char 75)
PS F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master> python ms_rewards_farmer.py --fast
Traceback (most recent call last):
  File "F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1119, in <module>
    ACCOUNTS = json.load(open(account_path, "r"))
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 5 (char 75)
PS F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master> python ms_rewards_farmer.py --fast
Traceback (most recent call last):
  File "F:\Win Apps\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1119, in <module>
    ACCOUNTS = json.load(open(account_path, "r"))
  File "C:\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 5 (char 75)

**Comment by farshadz1997** [comment]
It's look like 'accounts.json' file is not in json format, as it said it need "," at line 4 and column 5. double check it

**Comment by yoyodolo** [comment]
its in  json format, also if i remove mobile agent, it works absolutely fine

**Comment by farshadz1997** [comment]
No, I meant there's typo in your file that it cannot be parsed, I think you forgot to put "," after your password, it's very common mistake. look at example:

    "username": "your username",
    "password": "your password",
    "mobile_user_agent": ""

**Comment by yoyodolo** [comment]
Thanks, that resolved the issue!
