### ISSUE TITLE
No module named 'pyotp'

### ISSUE THREAD

**Issue by heximing** [farshadz1997/Microsoft-Rewards-bot#258]
```
Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 17, in <module>
    import pyotp
ModuleNotFoundError: No module named 'pyotp'
```

adding "pyotp" in "requirements.txt" and installing it using pip fixed the problem.

**Comment by heximing** [comment]
However, the newest code (c7d070e) did not fix the infinite loop problem using "--edge" I mentioned in issue #219 

```
[FLAGS] headless: True
[FLAGS] error: True
[FLAGS] superfast: True
[FLAGS] edge: True
[FLAGS] no_images: True
[FLAGS] currency: USD
[FLAGS] dont_check_for_updates: True

[LOGS] Logs loaded successfully.

********************t6172996924@hotmail.com********************

DevTools listening on ws://127.0.0.1:52270/devtools/browser/e866d9d4-2e19-4b1b-ad66-489cb86ab2fb
[LOGIN] Logging-in...
Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2536, in farmer
    login(browser, account['username'], account['password'], account.get('totpSecret', None))
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 242, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 533, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(
  File "C:\D\Python\WPy32-31090\python-3.10.9\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF60210DF92+60274]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF60209EBF2+818946]
        (No symbol) [0x00007FF601D2DFAE]
        (No symbol) [0x00007FF601D6FAA1]
        (No symbol) [0x00007FF601D6FC28]
        (No symbol) [0x00007FF601DAB687]
        (No symbol) [0x00007FF601D8F5AF]
        (No symbol) [0x00007FF601D62751]
        (No symbol) [0x00007FF601DA891C]
        (No symbol) [0x00007FF601D8F343]
        (No symbol) [0x00007FF601D61796]
        (No symbol) [0x00007FF601D60975]
        (No symbol) [0x00007FF601D61F04]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF601FA27D7+1593703]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF601E4AC5D+185837]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF601FDFD47+36951]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF601FD7E55+4453]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6022DFDB3+1319011]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A6CAC+851900]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A2D14+835620]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A2E6C+835964]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF602098A41+793937]
        BaseThreadInitThunk [0x00007FF99AE87604+20]
        RtlUserThreadStart [0x00007FF99BFC26A1+33]



********************t6172996924@hotmail.com********************

DevTools listening on ws://127.0.0.1:52344/devtools/browser/60b6af65-4d43-408a-baf7-36f3724a5dde
[LOGIN] Logging-in...
Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2536, in farmer
    login(browser, account['username'], account['password'], account.get('totpSecret', None))
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 242, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 533, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(
  File "C:\D\Python\WPy32-31090\python-3.10.9\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF60210DF92+60274]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF60209EBF2+818946]
        (No symbol) [0x00007FF601D2DFAE]
        (No symbol) [0x00007FF601D6FAA1]
        (No symbol) [0x00007FF601D6FC28]
        (No symbol) [0x00007FF601DAB687]
        (No symbol) [0x00007FF601D8F5AF]
        (No symbol) [0x00007FF601D62751]
        (No symbol) [0x00007FF601DA891C]
        (No symbol) [0x00007FF601D8F343]
        (No symbol) [0x00007FF601D61796]
        (No symbol) [0x00007FF601D60975]
        (No symbol) [0x00007FF601D61F04]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF601FA27D7+1593703]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF601E4AC5D+185837]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF601FDFD47+36951]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF601FD7E55+4453]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6022DFDB3+1319011]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A6CAC+851900]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A2D14+835620]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A2E6C+835964]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF602098A41+793937]
        BaseThreadInitThunk [0x00007FF99AE87604+20]
        RtlUserThreadStart [0x00007FF99BFC26A1+33]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2536, in farmer
    login(browser, account['username'], account['password'], account.get('totpSecret', None))
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 242, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 533, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(
  File "C:\D\Python\WPy32-31090\python-3.10.9\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF60210DF92+60274]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF60209EBF2+818946]
        (No symbol) [0x00007FF601D2DFAE]
        (No symbol) [0x00007FF601D6FAA1]
        (No symbol) [0x00007FF601D6FC28]
        (No symbol) [0x00007FF601DAB687]
        (No symbol) [0x00007FF601D8F5AF]
        (No symbol) [0x00007FF601D62751]
        (No symbol) [0x00007FF601DA891C]
        (No symbol) [0x00007FF601D8F343]
        (No symbol) [0x00007FF601D61796]
        (No symbol) [0x00007FF601D60975]
        (No symbol) [0x00007FF601D61F04]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF601FA27D7+1593703]
        Microsoft::Applications::Events::EventProperties::SetLevel [0x00007FF601E4AC5D+185837]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF601FDFD47+36951]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF601FD7E55+4453]
        Microsoft::Applications::Events::ILogManager::DispatchEventBroadcast [0x00007FF6022DFDB3+1319011]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A6CAC+851900]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A2D14+835620]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6020A2E6C+835964]
        Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF602098A41+793937]
        BaseThreadInitThunk [0x00007FF99AE87604+20]
        RtlUserThreadStart [0x00007FF99BFC26A1+33]
```
By the way, I use "--headless --error --superfast --no-images --dont-check-for-updates --edge --currency USD"
