### ISSUE TITLE
Log in error

### ISSUE THREAD

**Issue by heximing** [farshadz1997/Microsoft-Rewards-bot#279]
```
            by @Charlesbel upgraded by @Farshadz1997        version 5f1f2fb

[FLAGS] headless: True
[FLAGS] error: True
[FLAGS] superfast: True
[FLAGS] no_images: True
[FLAGS] currency: USD
[FLAGS] dont_check_for_updates: True

[LOGS] Logs loaded successfully.

********************@gmail.com********************

DevTools listening on ws://127.0.0.1:51660/devtools/browser/f155be98-e353-4623-9215-8817447879fe
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
Traceback (most recent call last):
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 2610, in farmer
    login(browser, account['username'], account['password'], account.get('totpSecret', None))
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 318, in login
    waitToLoadBlankPage()
  File "C:\D\Python\Microsoft-Rewards-bot-master(Edge)\ms_rewards_farmer.py", line 197, in waitToLoadBlankPage
    wait.until(ec.presence_of_element_located((By.TAG_NAME, "body")))
  File "C:\D\Python\WPy64-31090\python-3.10.9.amd64\lib\site-packages\selenium\webdriver\support\wait.py", line 81, in until
    value = method(self._driver)
  File "C:\D\Python\WPy64-31090\python-3.10.9.amd64\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in _predicate
    return driver.find_element(*locator)
  File "C:\D\Python\WPy64-31090\python-3.10.9.amd64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 855, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\D\Python\WPy64-31090\python-3.10.9.amd64\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\D\Python\WPy64-31090\python-3.10.9.amd64\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from no such window
  (Session info: chrome=112.0.5615.121)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x004DDCE3+50899]
        (No symbol) [0x0046E111]
        (No symbol) [0x00375450]
        (No symbol) [0x0036879A]
        (No symbol) [0x00367118]
        (No symbol) [0x0036778A]
        (No symbol) [0x00370B74]
        (No symbol) [0x0037AB28]
        (No symbol) [0x0037D4D6]
        (No symbol) [0x00367AE3]
        (No symbol) [0x0037A835]
        (No symbol) [0x003CDF77]
        (No symbol) [0x003BB6F6]
        (No symbol) [0x00397708]
        (No symbol) [0x0039886D]
        GetHandleVerifier [0x00743EAE+2566302]
        GetHandleVerifier [0x007792B1+2784417]
        GetHandleVerifier [0x0077327C+2759788]
        GetHandleVerifier [0x00575740+672048]
        (No symbol) [0x00478872]
        (No symbol) [0x004741C8]
        (No symbol) [0x004742AB]
        (No symbol) [0x004671B7]
        BaseThreadInitThunk [0x76C50099+25]
        RtlGetAppContainerNamedObjectPath [0x77587B6E+286]
        RtlGetAppContainerNamedObjectPath [0x77587B3E+238]



********************@gmail.com********************

DevTools listening on ws://127.0.0.1:51692/devtools/browser/5c3209e7-e0ac-4cb0-8233-b33a50639266
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
```
I tried both --edge and default chrome. Neither works.

**Comment by farshadz1997** [comment]
On the second try, it looks like it did login successfully.

**Comment by heximing** [comment]
> On the second try, it looks like it did login successfully.

It does not. It shows the same error again and again. I just copied and pasted a portion of the codes. The error tried again and again forever.

**Comment by royaltongue** [comment]
I'm also seeing this error today. It was working the other day, but I did just update to the latest version. Is your login also getting blocked by a request to enter a code sent to your email?

**Comment by farshadz1997** [comment]
I added a delay to handle this.
