### ISSUE TITLE
UNKNOWN ERROR!

### ISSUE THREAD

**Issue by LEARNERBE** [farshadz1997/Microsoft-Rewards-bot#281]
[UPDATER] Your version (5f1f2fb) is up to date!
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2916, in <module>
    main()
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2869, in main
    logs()
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1798, in logs
    LOGS = json.load(
           ^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Expecting value: line 1 column 1 (char 0)
press Enter to close...

**Comment by farshadz1997** [comment]
there's problem with your logs file, delete it and try again

**Comment by Prabh-Saini** [comment]
it looks like he tried deleting it all which caused it to crash because its a json file and it still needs:
```
[
]
```
as farshadz mentioned, just delete Logs_accounts.txt and retry.

**Comment by pujirino** [comment]
where i can find a log file?

**Comment by farshadz1997** [comment]
delete log file and try again.
