### ISSUE TITLE
"No such file or directory: 'nul' " and "cannot access local variable 'browser' where it is not associated with a value"

### ISSUE THREAD

**Issue by 569747257512165377** [farshadz1997/Microsoft-Rewards-bot#290]
The program gives two errors, shown below.

**Comment by 569747257512165377** [comment]
[UPDATER] Your version (a9a403e) is up to date!

[LOGS] Logs loaded successfully.

********************Your Email********************


Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2638, in farmer
    browser = browserSetup(
              ^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 177, in browserSetup
    service=Service(ChromeDriverManager().install()), options=options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 26, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\driver_cache.py", line 79, in find_driver
    browser_version = driver.get_browser_version_from_os()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\driver.py", line 67, in get_browser_version_from_os
    self._browser_version = get_browser_version_from_os(self.get_browser_type())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\utils.py", line 143, in get_browser_version_from_os
    OSType.WIN: windows_browser_apps_to_cmd(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\utils.py", line 122, in windows_browser_apps_to_cmd
    powershell = determine_powershell()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\webdriver_manager\core\utils.py", line 247, in determine_powershell
    with subprocess.Popen(
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 892, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1334, in _get_handles
    p2cread = msvcrt.get_osfhandle(self._get_devnull())
                                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1135, in _get_devnull
    self._devnull = os.open(os.devnull, os.O_RDWR)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2956, in <module>
    main()
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2910, in main
    farmer()
  File "C:\Users\user\Downloads\Microsoft-Rewards-bot-master\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 2847, in farmer
    if browser is not None:
       ^^^^^^^
UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value
cannot access local variable 'browser' where it is not associated with a value
press Enter to close...

**Comment by 569747257512165377** [comment]
both chromedriver.exe and msedgedriver.exe are in the bot directory, System32, and the PATH environment variable

**Comment by farshadz1997** [comment]
Try with --no-wevdriver-manager
