### ISSUE TITLE
Variable "Browser" referenced before assignment

### ISSUE THREAD

**Issue by lorehaze** [farshadz1997/Microsoft-Rewards-bot#291]
Running on Raspberry pi zero on "Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux" 

Chromium is Installed.

here the stack trace:

Traceback (most recent call last):
  File "/home/pi/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2641, in farmer
    browser = browserSetup(
  File "/home/pi/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 180, in browserSetup
    service=Service(ChromeDriverManager().install()), options=options)
  File "/home/pi/.local/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/pi/.local/lib/python3.9/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
  File "/home/pi/.local/lib/python3.9/site-packages/webdriver_manager/core/download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
  File "/home/pi/.local/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 37, in get
    self.validate_response(resp)
  File "/home/pi/.local/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_linux32.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2959, in <module>
    main()
  File "/home/pi/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2913, in main
    farmer()
  File "/home/pi/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2850, in farmer
    if browser is not None:
UnboundLocalError: local variable 'browser' referenced before assignment
local variable 'browser' referenced before assignment

**Comment by farshadz1997** [comment]
Use --no-webdriver-manager

**Comment by Prabh-Saini** [comment]
Hey mate, your only the twenty-seventh person to have this issue, if you took a glance at solved issues you could've found a solution. But here we are, so basically Webdriver Manager doesn't work because your using a Raspberry Pi, this is because ChromeDriver, and EdgeDriver don't support ARM Linux devices. (ChromeDriver does support ARM Mac, and EdgeDriver supports ARM Mac, and ARM Windows). You can download the ARM Linux equivalent by running `sudo apt-get install chromium-chromedriver` on your Raspberry Pi. Whilst using `--no-webdriver-manager`, if your Raspberry Pi is headless (not connected to a monitor), then also run `--virtual-display`. 🚀
