### ISSUE TITLE
Having issue running script on Oracle Arm Free Tier

### ISSUE THREAD

**Issue by ItzHecker404** [farshadz1997/Microsoft-Rewards-bot#302]
Used - python3 ms_rewards_farmer.py --session --superfast --no-webdriver-manager

Output 

Traceback (most recent call last):
  File "/home/ubuntu/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2655, in farmer
    browser = browserSetup(
  File "/home/ubuntu/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 178, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Could not remove old devtools port file. Perhaps the given user-data-dir at /home/ubuntu/Microsoft-Rewards-bot/Profiles/Nigha6601@outlook.com/PC is still attached to a running Chrome or Chromium process
Stacktrace:
#0 0xaaaae5902430 <unknown>
#1 0xaaaae566d7cc <unknown>
#2 0xaaaae5695064 <unknown>
#3 0xaaaae568fe18 <unknown>
#4 0xaaaae568ed8c <unknown>
#5 0xaaaae56c96c8 <unknown>
#6 0xaaaae56c8fe0 <unknown>
#7 0xaaaae5698308 <unknown>
#8 0xaaaae56992e4 <unknown>
#9 0xaaaae58cab30 <unknown>
#10 0xaaaae58cd8a8 <unknown>
#11 0xaaaae58cdef8 <unknown>
#12 0xaaaae58d5a70 <unknown>
#13 0xaaaae58ce614 <unknown>
#14 0xaaaae58a8c54 <unknown>
#15 0xaaaae58ed770 <unknown>
#16 0xaaaae58ed900 <unknown>
#17 0xaaaae58faa5c <unknown>
#18 0xffff967dc624 <unknown>
#19 0xffff9631149c <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2976, in <module>
    main()
  File "/home/ubuntu/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2924, in main
    farmer()
  File "/home/ubuntu/Microsoft-Rewards-bot/ms_rewards_farmer.py", line 2864, in farmer
    if browser is not None:
UnboundLocalError: local variable 'browser' referenced before assignment
local variable 'browser' referenced before assignment

Tried --headless and --virtual-display as well
but same error always,  it's an oracle free tier vps arm structure

**Comment by farshadz1997** [comment]
try without --session

**Comment by ItzHecker404** [comment]
> try without --session

Yup working without session, Any way to solve it so the accounts are safe with session ?

**Comment by richard892** [comment]
> > try without --session
> 
> Yup tried now worked without --session, Any way to solve it so the accounts are safe with session ?

how much RAM "Oracle Arm Free Tier" provides?

**Comment by akshatj27** [comment]
> > > try without --session
> > 
> > 
> > Yup tried now worked without --session, Any way to solve it so the accounts are safe with session ?
> 
> how much RAM "Oracle Arm Free Tier" provides?

24 gb

**Comment by richard892** [comment]
> > > > try without --session
> > > 
> > > 
> > > Yup tried now worked without --session, Any way to solve it so the accounts are safe with session ?
> > 
> > 
> > how much RAM "Oracle Arm Free Tier" provides?
> 
> 24 gb

are you also grinding on oracle free tier?

**Comment by anilabhadatta** [comment]
python ms_rewards_farmer.py --session --superfast --dont-check-for-updates --no-webdriver-manager
I am using this command and working fine.
TRY CREATING VIRTUALENV AND ACTIVATE THE ENV AND INSTALL THE PYTHON PACKAGES

**Comment by akshatj27** [comment]
> > > > > try without --session
> > > > 
> > > > 
> > > > Yup tried now worked without --session, Any way to solve it so the accounts are safe with session ?
> > > 
> > > 
> > > how much RAM "Oracle Arm Free Tier" provides?
> > 
> > 
> > 24 gb
> 
> are you also grinding on oracle free tier?

not anymore, was having issues with the session.
