### ISSUE TITLE
Problem with running parallel (Multiple) on Ubuntu

### ISSUE THREAD

**Issue by KevinNitroG** [farshadz1997/Microsoft-Rewards-bot#366]
Hi, it's me again, the guy who created the scripts for your bot to run on GA _(ubuntu)_
I'm developing the script to run the bot parallelly, but seem that the bot has a problem when running more than 1 task. I have checked the accounts.json and there was no mistake there, also tested it on windows and it worked fine. I tried running only 1 task and it got not problem.

Here is the error log of running more than 1 task _(particularly 2 parallel tasks)_
```
███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗ 
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version ec6c5da

[FLAGS] error: True
[FLAGS] superfast: True
[FLAGS] on_finish: exit
[FLAGS] skip_unusual: True
[FLAGS] no_images: True
[FLAGS] virtual_display: True
[FLAGS] dont_check_for_updates: True
[FLAGS] repeat_shopping: True
[FLAGS] accounts_file: ['accounts_1.json']

[LOGS] "Logs_accounts_1.txt" file not found.
[LOGS] "Logs_accounts_1.txt" created.

********************mail********************

[WDM] - Downloading:   0%|          | 0.00/6.98M [00:00<?, ?B/s]

    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗ 
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version ec6c5da

[FLAGS] error: True
[FLAGS] superfast: True
[FLAGS] on_finish: exit
[FLAGS] skip_unusual: True
[FLAGS] no_images: True
[FLAGS] virtual_display: True
[FLAGS] dont_check_for_updates: True
[FLAGS] repeat_shopping: True
[FLAGS] accounts_file: ['accounts_2.json']

[LOGS] "Logs_accounts_2.txt" file not found.
[LOGS] "Logs_accounts_2.txt" created.

********************mail********************
[WDM] - Downloading:   0%|          | 0.00/6.98M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 6.98M/6.98M [00:00<00:00, 1[40](https://github.com/KevinNitroK/MSRB-GA-test/actions/runs/4970586358/jobs/8894548787#step:8:41)MB/s]

[WDM] - Downloading: 100%|██████████| 6.98M/6.98M [00:00<00:00, 112MB/s]
File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 2701, in farmer
Traceback (most recent call last):
    browser = browserSetup(
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 2701, in farmer

    browser = browserSetup(
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 178, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 26] Text file busy: '/home/runner/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 3040, in <module>
    main()
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 2987, in main
    farmer()
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 2927, in farmer
    if browser is not None:
UnboundLocalError: local variable 'browser' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 30[43](https://github.com/KevinNitroK/MSRB-GA-test/actions/runs/4970586358/jobs/8894548787#step:8:44), in <module>
    input("press Enter to close...")
EOFError: EOF when reading a line
  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 178, in browserSetup
    browser = webdriver.Chrome(options=options) if ARGS.no_webdriver_manager else webdriver.Chrome(

  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",

  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()

  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,

  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
[Errno 26] Text file busy: '/home/runner/.wdm/drivers/chromedriver/linux64/113.0.[56](https://github.com/KevinNitroK/MSRB-GA-test/actions/runs/4970586358/jobs/8894548787#step:8:57)72.[63](https://github.com/KevinNitroK/MSRB-GA-test/actions/runs/4970586358/jobs/8894548787#step:8:64)/chromedriver'


File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 3040, in <module>
    main()

  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 29[87](https://github.com/KevinNitroK/MSRB-GA-test/actions/runs/4970586358/jobs/8894548787#step:8:88), in main
    farmer()

  File "/home/runner/work/MSRB-GA-test/MSRB-GA-test/MSRB/1/ms_rewards_farmer.py", line 2[92](https://github.com/KevinNitroK/MSRB-GA-test/actions/runs/4970586358/jobs/8894548787#step:8:93)7, in farmer
    if browser is not None:
local variable 'browser' referenced before assignment
```

**Comment by farshadz1997** [comment]
Hi,

it says your web driver is busy, this is not the correct way to parallel

**Comment by KevinNitroG** [comment]
> Hi,
> 
> it says your web driver is busy, this is not the correct way to parallel

Oh alright thank you 😁
