### ISSUE TITLE
Errors when running on Windows

### ISSUE THREAD

**Issue by HQModz** [farshadz1997/Microsoft-Rewards-bot#70]
Hello, I am getting the following errors when starting the bot on Windows. Can you please assist? Thank you!

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Bots\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1300, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\Bots\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 82, in browserSetup
    browser = webdriver.Chrome(options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\Bots\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1424, in <module>
    main()
  File "C:\Users\Admin\Desktop\Bots\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1411, in main
    farmer()
  File "C:\Users\Admin\Desktop\Bots\Microsoft-Rewards-bot-master\ms_rewards_farmer.py", line 1375, in farmer
    browser.quit()
    ^^^^^^^
UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value

**Comment by HQModz** [comment]
Resolved by putting the chrome driver executable in the bot path. Thanks!
