### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gnaagounet** [farshadz1997/Microsoft-Rewards-bot#75]
Hello, 

When I execute the script, I get this error after accepting to start it immediately

Traceback (most recent call last):
  File "/home/gnaag/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 1424, in <module>
    main()
  File "/home/gnaag/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 1410, in main
    logs()
  File "/home/gnaag/Microsoft-Rewards-bot-master/ms_rewards_farmer.py", line 1119, in logs
    LOGS = json.load(open(f"{Path(__file__).parent}/Logs_{account_path.stem}.txt", "r"))
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Rickyose** [comment]
did you do this:

1. install python?
2. `pip install -r requirements.txt`
3. Download chromedriver and put it in Place the file in X:\Windows (X as your Windows disk letter)

**Comment by farshadz1997** [comment]
There's a typo in your accounts.json file

**Comment by Gnaagounet** [comment]
Thank you, it was not the accounts.json (I moved it to recreate another one by the py script and the issue was the same), but the logs file. Curiously, I never write in this file but anyway, it works now

**Comment by farshadz1997** [comment]
Yes it was your logs, my bad
