### ISSUE TITLE
Error when running the bot

### ISSUE THREAD

**Issue by hantraxer0craft** [farshadz1997/Microsoft-Rewards-bot#77]
Yo
When I run the program I get the error _UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value_

> The full error 
C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot>python ms_rewards_farmer.py --session --edge
    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version 2.1
[INFO] everyday : None
[INFO] headless : False
[INFO] session : True
[INFO] error : False
[INFO] fast : False
[INFO] telegram : None
[INFO] discord : None
[INFO] edge : True
[INFO] shutdown : False
If you want to run the program at a specific time, type your desired time in 24h format (HH:MM) else press Enter
(anything other than time causes the script to start immediately):
[LOGS] Logs loaded successfully.
********************random@random.com********************
Traceback (most recent call last):
  File "C:\Users\phasl\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phasl\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\phasl\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1300, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 80, in browserSetup
    browser = webdriver.Edge(options=options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phasl\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\edge\webdriver.py", line 61, in __init__
    super().__init__(DesiredCapabilities.EDGE['browserName'], "ms",
  File "C:\Users\phasl\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 89, in __init__
    self.service.start()
  File "C:\Users\phasl\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'msedgedriver' executable needs to be in PATH. Please download from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1424, in <module>
    main()
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1411, in main
    farmer()
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1375, in farmer
    browser.quit()
    ^^^^^^^
UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value

**Comment by farshadz1997** [comment]
Hello,
it seems like you don't have Edge web driver, download it from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/ and put it in Bot directory.

**Comment by hantraxer0craft** [comment]
Re 
The bot worked successfuly for 2days and after that I got this error

> Traceback (most recent call last):
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1424, in <module>
    main()
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1410, in main
    logs()
  File "C:\Users\phasl\OneDrive\Bureau\Microsoft-Rewards-bot\ms_rewards_farmer.py", line 1123, in logs
    shared_items.append(user['username'])
                        ~~~~^^^^^^^^^^^^
KeyError: 'username'

**Comment by hantraxer0craft** [comment]
Ah no I found the solution but thx

**Comment by farshadz1997** [comment]
you had typo in ```accounts.json```, it was looking for ```username``` but didn't find it.
