### ISSUE TITLE
UnboundLocalError: local variable 'browser' referenced before assignment

### ISSUE THREAD

**Issue by Rain623** [farshadz1997/Microsoft-Rewards-bot#96]
Ubuntu-20.04.1-x64
```
$ python3 ms_rewards_farmer.py 
sh: 1: color: not found

    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗ 
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version 2.1


[LOGS] Logs loaded successfully.

********************xxx@xxx.com********************


Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 1471, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
  File "ms_rewards_farmer.py", line 88, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "/home/water/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/water/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/water/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/water/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/water/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/water/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /snap/chromium/2295/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5561c46df0a3 <unknown>
#1 0x5561c44b8247 <unknown>
#2 0x5561c44e01d8 <unknown>
#3 0x5561c44dc3cf <unknown>
#4 0x5561c451cbb6 <unknown>
#5 0x5561c4513f43 <unknown>
#6 0x5561c44e7602 <unknown>
#7 0x5561c44e876e <unknown>
#8 0x5561c472ad76 <unknown>
#9 0x5561c472d7db <unknown>
#10 0x5561c472e02a <unknown>
#11 0x5561c47145ae <unknown>
#12 0x5561c472e7bc <unknown>
#13 0x5561c4706308 <unknown>
#14 0x5561c474cb98 <unknown>
#15 0x5561c474cd35 <unknown>
#16 0x5561c4767194 <unknown>
#17 0x7fe1f0499609 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 1602, in <module>
    main()
  File "ms_rewards_farmer.py", line 1588, in main
    farmer()
  File "ms_rewards_farmer.py", line 1548, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
```

**Comment by farshadz1997** [comment]
Check the version compatibility between the Chrome browser and ChromeDriver: Make sure that you're using the correct version of ChromeDriver that matches the version of the Chrome browser you have installed.

**Comment by JonrGull** [comment]
@farshadz1997 sorry to bring this up but I'm stuck. I'm using WSL and downloaded chrome ver 110.0.5481.177.
When I run 
`sudo apt install chromium-chromedriver` it installs 1:85.0.4183.83-0ubuntu2. That can't be correct, right?

Thanks for any help.

**Comment by AG4lyf** [comment]
this will not work without a display attached. if you insist to override the limit you can use `export DISPLAY=:0 ` before starting the python file. saying that its a actual display. if you wanna confirm the value. open a terminal window in actual GUI and type `printenv` and look for DISPLAY

**Comment by q123458384** [comment]
the same question on Ubuntu-20.04.1-x64

**Comment by KaushikDuddala** [comment]
try running "sudo apt install chromium-chromedriver" and then using the --no-webdriver-manager flag
