### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by Skeppr** [farshadz1997/Microsoft-Rewards-bot#98]
whenever i launch it it gives me error

```
ccapy@heniu-PC:~/msrewards2/Microsoft-Rewards-bot$ sudo python3 ms_rewards_farmer.py --fast
sh: 1: color: not found

    ███╗   ███╗███████╗    ███████╗ █████╗ ██████╗ ███╗   ███╗███████╗██████╗
    ████╗ ████║██╔════╝    ██╔════╝██╔══██╗██╔══██╗████╗ ████║██╔════╝██╔══██╗
    ██╔████╔██║███████╗    █████╗  ███████║██████╔╝██╔████╔██║█████╗  ██████╔╝
    ██║╚██╔╝██║╚════██║    ██╔══╝  ██╔══██║██╔══██╗██║╚██╔╝██║██╔══╝  ██╔══██╗
    ██║ ╚═╝ ██║███████║    ██║     ██║  ██║██║  ██║██║ ╚═╝ ██║███████╗██║  ██║
    ╚═╝     ╚═╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚═╝  ╚═╝
            by @Charlesbel upgraded by @Farshadz1997        version 2.1

[INFO] everyday: False
[INFO] headless: False
[INFO] session: False
[INFO] error: False
[INFO] fast: True
[INFO] telegram: None
[INFO] discord: None
[INFO] edge: False
[INFO] shutdown: None
[INFO] account_browser: None
[INFO] start_at: None

[LOGS] Logs loaded successfully.

********************myemailiscorrect_dw********************


Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 1471, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
  File "ms_rewards_farmer.py", line 88, in browserSetup
    browser = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 1602, in <module>
    main()
  File "ms_rewards_farmer.py", line 1588, in main
    farmer()
  File "ms_rewards_farmer.py", line 1548, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
ccapy@heniu-PC:~/msrewards2/Microsoft-Rewards-bot$
```

**Comment by zuiyiweiyuanzui** [comment]
I also have this problem. This problem also occurs when running on centos system

**Comment by farshadz1997** [comment]
The error message "selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 1" usually indicates that the ChromeDriver service has crashed. Here are some steps you can try to fix this issue:

1. Check the version compatibility between the Chrome browser and ChromeDriver: Make sure that you're using the correct version of ChromeDriver that matches the version of the Chrome browser you have installed.

2. Update ChromeDriver: If you have an older version of ChromeDriver, try updating to the latest version. You can download the latest version from the official Chromium project website.

3. Reinstall ChromeDriver: If updating doesn't resolve the issue, try uninstalling and reinstalling ChromeDriver.

4. Check for conflicting installations: If you have multiple installations of ChromeDriver on your system, it might be causing the service to crash. Try uninstalling any conflicting installations.

**Comment by zuiyiweiyuanzui** [comment]
Hello, I have re-installed Chrome browser and ChromeDriver, but it still doesn't work, can you run it on centos?

**Comment by farshadz1997** [comment]
No, I just have Ubuntu and Windows

**Comment by zuiyiweiyuanzui** [comment]
Ok, I would like to ask if you have encountered this problem running on ubuntu?

**Comment by farshadz1997** [comment]
It runs flawlessly on Ubuntu

**Comment by zuiyiweiyuanzui** [comment]
ok，thanks

**Comment by fwobbly** [comment]
> 
I had this issue just now, all I did was delete the "Logs_accounts.txt" file and the farmer resets.
I assume this is because the chrome browser did not load in correctly,, so the farmer just automatically tells the error instead of retrying to confirm.

**Comment by Prabh-Saini** [comment]
solved? @farshadz1997

**Comment by farshadz1997** [comment]
@Prabh-Saini I couldn't simulate this error on my device to find a fix for this problem
